### ISSUE TITLE
Setup local env fails

### ISSUE THREAD

**Issue by imod** [3scale/APIcast#1375]
Hi,

I'm trying to setup a local environment to develop a custom policy, but I fail to get APIcast up and running as described...

##### Version

`master` branch

##### Steps To Reproduce

1. `git clone git@github.com:3scale/APIcast.git`
2. `cd APIcast`
3. `make development`
4. `make dependencies` --> fails

##### Current Result

```
domi 🙈 APIcast $ make development
Running on Darwin
docker compose -f docker-compose-devel.yml -f docker-compose-devel-volmount-mac.yml up -d
[+] Running 2/2
 ⠿ Container apicast_build_0-redis-1        Running                                                                            0.0s
 ⠿ Container apicast_build_0-development-1  Started                                                                            1.5s
docker compose -f docker-compose-devel.yml -f docker-compose-devel-volmount-mac.yml exec -e COLUMNS="`tput cols`" -e LINES="`tput lines`" --user 501:20 development bash
bash-4.4$ make dependencies
/usr/local/openresty/luajit/bin/rover lock --roverfile=/opt/app-root/src/gateway/Roverfile
Resolving /opt/app-root/src/gateway/Roverfile
Cloning into 'lua-resty-repl'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Connection refused

/usr/local/openresty/luajit/bin/luajit-2.1.0-beta3: /usr/share/lua/5.1/rover/lock.lua:169: attempt to index local 'rockspec' (a nil value)
stack traceback:
        /usr/share/lua/5.1/rover/lock.lua:169: in function 'expand_dependencies'
        /usr/share/lua/5.1/rover/lock.lua:199: in function 'resolve'
        /usr/share/lua/5.1/rover/cli/lock.lua:23: in function </usr/share/lua/5.1/rover/cli/lock.lua:11>
        /usr/share/lua/5.1/rover/cli.lua:33: in function </usr/share/lua/5.1/rover/cli.lua:27>
        /usr/lib64/luarocks/rocks/lua-rover/scm-1/bin/rover:8: in main chunk
        [C]: at 0x55ad138087a0
make: *** [Makefile:214: /opt/app-root/src/gateway/Roverfile.lock] Error 1
bash-4.4$ ^C
bash-4.4$ exit
```

##### Additional Information

* I tried to access github.com from within the running container, it works with `git` (ssh and https) and `curl` (https)

**Comment by eguzki** [comment]
That is because some lua deps have `git://github.com/` as source and github, for [security reasons](https://github.blog/2021-09-01-improving-git-protocol-security-github/) removed git plain protocol. 

The proper fix should be done in the lua deps repos, replacing `git://github.com/` with `git@github.com` or `ssh://github.com`. In the meantime, the workaround is to update your git configuration, i.e. in `.gitconfig` adding
```
[url "https://github.com/"]
	insteadOf = git://github.com/
```

That should do it

**Comment by imod** [comment]
thanks @eguzki ! It does get me further, but now it fails with this...
```
domi 🙈 APIcast $ make development
Running on Darwin
docker-compose -f docker-compose-devel.yml -f docker-compose-devel-volmount-mac.yml up -d
Creating network "apicast_build_0_default" with the default driver
Creating apicast_build_0_redis_1 ... done
Creating apicast_build_0_development_1 ... done
docker-compose -f docker-compose-devel.yml -f docker-compose-devel-volmount-mac.yml exec -e COLUMNS="`tput cols`" -e LINES="`tput lines`" --user 501:20 development bash
bash-4.4$ git config --global url.https://github.com/.insteadOf git://github.com/
bash-4.4$ cat ~/.gitconfig 
[url "https://github.com/"]
	insteadOf = git://github.com/
bash-4.4$ make dependencies
/usr/local/openresty/luajit/bin/rover lock --roverfile=/opt/app-root/src/gateway/Roverfile
Resolving /opt/app-root/src/gateway/Roverfile
Cloning into 'lua-resty-repl'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 52 (delta 3), reused 36 (delta 0), pack-reused 0
Unpacking objects: 100% (52/52), 21.30 KiB | 474.00 KiB/s, done.
Note: switching to '3878f41b7e8f97b1c96919db19dbee9496569dda'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

/usr/local/openresty/luajit/bin/luajit-2.1.0-beta3: /usr/share/lua/5.1/rover/lock.lua:169: attempt to index local 'rockspec' (a nil value)
stack traceback:
	/usr/share/lua/5.1/rover/lock.lua:169: in function 'expand_dependencies'
	/usr/share/lua/5.1/rover/lock.lua:199: in function 'resolve'
	/usr/share/lua/5.1/rover/cli/lock.lua:23: in function </usr/share/lua/5.1/rover/cli/lock.lua:11>
	/usr/share/lua/5.1/rover/cli.lua:33: in function </usr/share/lua/5.1/rover/cli.lua:27>
	/usr/lib64/luarocks/rocks/lua-rover/scm-1/bin/rover:8: in main chunk
	[C]: at 0x55ceb66087a0
make: *** [Makefile:214: /opt/app-root/src/gateway/Roverfile.lock] Error 1
bash-4.4$
```

**Comment by eguzki** [comment]
Actually, my hint about the git configuration is not needed, because the Makefile already does that for us (target [translate_git_protocol](https://github.com/3scale/APIcast/blob/master/Makefile#L216) called as dependecy of the target `make dependencies`. So I do not know why helped a bit.

The error is about trying to load a dependecy that is not found

Which commitID of the master branch are you working on? 

Try to run `make  clean` that will remove local docker images so you make sure images being used are latest.

**Comment by eguzki** [comment]
Ok, this is something related to macos. We will fix that.

**Comment by imod** [comment]
@eguzki great, many thanks! can you please ping me once this is available?

**Comment by imod** [comment]
unfortunate I don't understand the issue (yet), but is there anything I can help with?

**Comment by eguzki** [comment]
I am waiting to have one macOS so I can dig into the issue. Some lua library is not being installed and the lua manager, rover, does not check when a dep is not found and when accessing the name, it crashes. That's all I can say until I can reproduce in a macOS and figure out which dep is not being found and why

**Comment by imod** [comment]
@eguzki maybe I can help you with some more details? just let me know what information you require and I'm happy to reproduce and provide it.
I really would like to get started with custom policies :)

**Comment by guicassolato** [comment]
I did some investigation on this today. Here are a couple changes to workaround the issues reported (until a proper fix is sent).

### 1. "Connection refused"

To avoid `Connection refused` and the extra `git config --global url.https://github.com/.insteadOf git://github.com` command, which should not be needed.

Error:

```
bash-4.4$ make dependencies
/usr/local/openresty/luajit/bin/rover lock --roverfile=/opt/app-root/src/gateway/Roverfile
Resolving /opt/app-root/src/gateway/Roverfile
Cloning into 'lua-resty-repl'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Connection refused

/usr/local/openresty/luajit/bin/luajit-2.1.0-beta3: /usr/share/lua/5.1/rover/lock.lua:169: attempt to index local 'rockspec' (a nil value)
stack traceback:
	/usr/share/lua/5.1/rover/lock.lua:169: in function 'expand_dependencies'
	/usr/share/lua/5.1/rover/lock.lua:199: in function 'resolve'
	/usr/share/lua/5.1/rover/cli/lock.lua:23: in function </usr/share/lua/5.1/rover/cli/lock.lua:11>
	/usr/share/lua/5.1/rover/cli.lua:33: in function </usr/share/lua/5.1/rover/cli.lua:27>
	/usr/lib64/luarocks/rocks/lua-rover/scm-1/bin/rover:8: in main chunk
	[C]: at 0x40000087a0
make: *** [Makefile:214: /opt/app-root/src/gateway/Roverfile.lock] Error 1
```

Fix:

```diff
diff --git a/Makefile b/Makefile
index dc8a667d..d1586798 100644
--- a/Makefile
+++ b/Makefile
@@ -216,7 +216,7 @@ $(GATEWAY_CONTEXT)/Roverfile.lock : $(GATEWAY_CONTEXT)/Roverfile $(GATEWAY_CONTE
 translate_git_protocol:
 	@git config --global url.https://github.com/.insteadOf git://github.com/
 
-lua_modules: $(ROVER) $(GATEWAY_CONTEXT)/Roverfile.lock translate_git_protocol
+lua_modules: $(ROVER) translate_git_protocol $(GATEWAY_CONTEXT)/Roverfile.lock
 # This variable is to skip issues with openssl 1.1.1
 # https://github.com/wahern/luaossl/issues/175
 	EXTRA_CFLAGS="-DHAVE_EVP_KDF_CTX=1" $(ROVER) install --roverfile=$(GATEWAY_CONTEXT)/Roverfile > /dev/null
```

### 2. "Rockspec format 3.0 not supported" (lua-resty-jwt v0.2.3) – the root cause of the [last issue](https://github.com/3scale/APIcast/issues/1375#issuecomment-1264931784) reported by @imod 

To avoid `attempt to index local 'rockspec' (a nil value)`, after fixing the git scheme and running `make dependencies`; caused by [lua-resty-jwt](https://luarocks.org/modules/cdbattags/lua-resty-jwt) with of the [addition of lua-resty-openssl](https://github.com/cdbattags/lua-resty-jwt/blob/b3d5c085643fa95099e72a609c57095802106ff9/lua-resty-jwt-dev-0.rockspec#L19) in v0.2.3 (see https://github.com/cdbattags/lua-resty-jwt/pull/44).

Error:

```
bash-4.4$ make dependencies
/usr/local/openresty/luajit/bin/rover lock --roverfile=/opt/app-root/src/gateway/Roverfile
Resolving /opt/app-root/src/gateway/Roverfile
/usr/local/openresty/luajit/bin/luajit-2.1.0-beta3: /usr/share/lua/5.1/rover/lock.lua:169: attempt to index local 'rockspec' (a nil value)
stack traceback:
	/usr/share/lua/5.1/rover/lock.lua:169: in function 'expand_dependencies'
	/usr/share/lua/5.1/rover/lock.lua:199: in function 'resolve'
	/usr/share/lua/5.1/rover/cli/lock.lua:23: in function </usr/share/lua/5.1/rover/cli/lock.lua:11>
	/usr/share/lua/5.1/rover/cli.lua:33: in function </usr/share/lua/5.1/rover/cli.lua:27>
	/usr/lib64/luarocks/rocks/lua-rover/scm-1/bin/rover:8: in main chunk
	[C]: at 0x40000087a0
make: *** [Makefile:214: /opt/app-root/src/gateway/Roverfile.lock] Error 1
```

Fix:

```diff
diff --git a/gateway/apicast-scm-1.rockspec b/gateway/apicast-scm-1.rockspec
index bac8c66a..bc7999e0 100644
--- a/gateway/apicast-scm-1.rockspec
+++ b/gateway/apicast-scm-1.rockspec
@@ -14,7 +14,7 @@ dependencies = {
    'inspect',
    'lyaml',
    'router',
-   'lua-resty-jwt',
+   'lua-resty-jwt == 0.2.0',
    'lua-resty-url',
    'lua-resty-env',
    'lua-resty-execvp',
```

### 3. "Could not find header file for PCRE" (jsonschema v0.9.8)

To avoid `Could not find header file for PCRE` (not reported here), after `rover lock` passes and `rover install` is executed by the `lua_modules` target; caused by [jsonschema](https://luarocks.org/modules/membphis/jsonschema) with the [addition of lrexlib-pcre](https://github.com/api7/jsonschema/blob/0096f5e5bfdd210136a98e9d50799d86b9bd040c/rockspec/jsonschema-0.9.8-0.rockspec#L23) in v0.9.8 (see https://github.com/api7/jsonschema/pull/76).

Error:
```
bash-4.4$ make dependencies
Resolved Roverfile.lock in 	142	s
EXTRA_CFLAGS="-DHAVE_EVP_KDF_CTX=1" /usr/local/openresty/luajit/bin/rover install --roverfile=/opt/app-root/src/gateway/Roverfile > /dev/null
[...]
/usr/local/openresty/luajit/bin/luajit-2.1.0-beta3: /usr/share/lua/5.1/rover/install.lua:59: Could not find header file for PCRE
  No file pcre.h in /usr/local/include
  No file pcre.h in /usr/include
You may have to install PCRE in your system and/or pass PCRE_DIR or PCRE_INCDIR to the luarocks command.
Example: luarocks install lrexlib-pcre PCRE_DIR=/usr/local
stack traceback:
	[C]: in function 'assert'
	/usr/share/lua/5.1/rover/install.lua:59: in function 'install'
	/usr/share/lua/5.1/rover/install.lua:102: in function 'call'
	/usr/share/lua/5.1/rover/cli/install.lua:42: in function </usr/share/lua/5.1/rover/cli/install.lua:19>
	/usr/share/lua/5.1/rover/cli.lua:33: in function </usr/share/lua/5.1/rover/cli.lua:27>
	/usr/lib64/luarocks/rocks/lua-rover/scm-1/bin/rover:8: in main chunk
	[C]: at 0x40000087a0
make: *** [Makefile:222: lua_modules] Error 1
```

Fix:
```diff
diff --git a/gateway/Roverfile b/gateway/Roverfile
index a331fe06..b0f16e93 100644
--- a/gateway/Roverfile
+++ b/gateway/Roverfile
@@ -9,7 +9,7 @@ luarocks {
     group 'testing' {
         module { 'busted' },
         module { 'luacov' },
-        module { 'jsonschema' },
+        module { 'jsonschema', '0.8' },
     },
 
     group 'development' {
```

<br/>

I have tested the above on macOS with M1 chip and the fixes make `make dependencies` pass. However, neither I have checked for regression on Linux, nor I can tell just yet if this is enough for the development environment to be fully functional on macOS.

After applying all the 3 fixes above and running `make dependencies` inside the development container, you should see the following output:

```
Complete! Modules were bundled into /opt/app-root/src/vendor/cache
```

----

_In time:_ I also observed the following error when trying to compile [luaossl](https://luarocks.org/modules/daurnimator/luaossl) at one of my attempts:

```
bash-4.4$ make dependencies
[...]
Resolved Roverfile.lock in 	142	s
EXTRA_CFLAGS="-DHAVE_EVP_KDF_CTX=1" /usr/local/openresty/luajit/bin/rover install --roverfile=/opt/app-root/src/gateway/Roverfile > /dev/null
Warning: skipping dependency checks.
No existing manifest. Attempting to rebuild...
Warning: skipping dependency checks.
Warning: skipping dependency checks.
Warning: skipping dependency checks.
Hunk 1 found at offset 2...
successfully patched /tmp/luarocks_luarocks-source-luaossl-20220711-0-oCpRgw/luaossl-rel-20220711/src/openssl.c
src/openssl.c:623:10: fatal error: openssl/core_names.h: No such file or directory
 #include <openssl/core_names.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/usr/local/openresty/luajit/bin/luajit-2.1.0-beta3: /usr/share/lua/5.1/rover/install.lua:59: Build error: Failed compiling object src/openssl.o
stack traceback:
	[C]: in function 'assert'
	/usr/share/lua/5.1/rover/install.lua:59: in function 'install'
	/usr/share/lua/5.1/rover/install.lua:102: in function 'call'
	/usr/share/lua/5.1/rover/cli/install.lua:42: in function </usr/share/lua/5.1/rover/cli/install.lua:19>
	/usr/share/lua/5.1/rover/cli.lua:33: in function </usr/share/lua/5.1/rover/cli.lua:27>
	/usr/lib64/luarocks/rocks/lua-rover/scm-1/bin/rover:8: in main chunk
	[C]: at 0x40000087a0
make: *** [Makefile:222: lua_modules] Error 1
```

Exiting the container and running `make clean`, `make development`, and then `make dependencies` again solved the issue for me.

**Comment by guicassolato** [comment]
> I have run on Linux with your fixes (in details), but unfortunately I have the issue
> 
> ```
> src/openssl.c:623:10: fatal error: openssl/core_names.h: No such file or directory
>  #include <openssl/core_names.h>
>           ^~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> ```
> 
> I cannot solve the issue running `make clean`, `make development` and then `make dependencies`.

@eguzki, you're right.

This is caused by the `luaossl` module version [20220711](https://luarocks.org/modules/daurnimator/luaossl/20220711-0), specifically https://github.com/wahern/luaossl/pull/199.

It is not a Linux nor macOS specific issue, but triggered whenever trying to compile this version of the module on any system with OpenSSL 1.1.1 while setting `HAVE_EVP_KDF_CTX=1`.

The root cause is [this fix](https://github.com/3scale/APIcast/commit/de53c522b4367b2f882cd649fcf583ad680dc4da) of ours, combined with [this](https://github.com/wahern/luaossl/blob/247c0d9e12d2c654284c259f8cdb2a6ecf9d81b5/src/openssl.c#L620-L626) requirement from luaossl 20220711) and the fact that OpenSSL 1.1.1 does not include the `core_names.h` file (see [openssl-1.1.1/includes](https://github.com/openssl/openssl/tree/OpenSSL_1_1_1-stable/include/openssl) vs [openssl-3.0/includes](https://github.com/openssl/openssl/tree/openssl-3.0/include/openssl)).

I have tried a few things to workaround this issue without bumping to OpenSSL 3.x or having to rebuild the devel image in local machine, but nothing worked given other constraints. I'll try a different approach tomorrow.

**Comment by eguzki** [comment]
Hi @imod,

Thanks to the great job from @guicassolato , the fix for aarch64 hosts was recently merged to `master`. 

Let us know if you can setup the local environment

**Comment by imod** [comment]
Thanks @eguzki and @guicassolato - I just tried to setup my local environment and so far everything seems to be working fine!
