### ISSUE TITLE
Fix OAuth

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [3scale/apicast#157]
[provide a description of the issue]
I am led to understand that OAuth is not working correctly in apicast at the moment.

Can anyone verify that?

##### Steps To Reproduce

1. [step 1 (json configuration file, if applies)]
2. [step 2 (curl commands to reproduce, if applies)]
3. [step 3]

##### Additional Information

* [Gist with minimal reproducible configuration, see guidelines for contributing for details]
* [Gist with nginx log output]

**Comment by mpguerra** [comment]
There are currently 2 issues when attempting to request an access token from the Gateway:

1. Authorization fails when requesting an authorization code, despite credentials being correct. This seems to be due to a missing host header when validating credentials against the 3scale backend

2. When exchanging the authorization code for an access token, the gateway fails to extract client credentials from Authorization header correctly due to string.split function not being imported or invoked correctly.

**Comment by mikz** [comment]
Missing test coverage https://github.com/3scale/apicast/pull/160
