### ISSUE TITLE
Fails to start 3scale gateway on openshift if redhat.registry is missing in yml

### ISSUE THREAD

**Issue by VinayBhalerao** [3scale/apicast#241]
Originally reported by RH SA:

My Local setup:
Mac and installed openshift using vagrant

RH SA local setup:
Mac and installed Openshift using oc cluster

On both setup the openshift fails to start. 

Error from deployment logs
```
Scaling threescalegw-1 to 2
Waiting up to 10m0s for pods in deployment threescalegw-1 to become ready
error: update acceptor rejected threescalegw-1: pods for deployment "threescalegw-1" took longer than 600 seconds to become ready
```

Below is the error from POD
```
Here is the log on the pod before it gets deleted:
2017/01/20 15:13:50 [error] 1#1: [lua] configuration.lua:344: init(): boot could not get configuration, 2017/01/20 15:13:51 [error] 26#26: *2 [lua] configuration.lua:501: curl(): configuration download error curl: (22) The requested URL returned error: 403 Forbidden
 22, context: ngx.timer
./src/configuration.lua:323: missing configuration
: 1
2017/01/20 15:13:50 [emerg] 1#1: [lua] apicast.lua:21: handle_missing_configuration(): failed to load configuration, exiting: 2017/01/20 15:13:51 [error] 26#26: *2 [lua] configuration.lua:501: curl(): configuration download error curl: (22) The requested URL returned error: 403 Forbidden
 22, context: ngx.timer
./src/configuration.lua:323: missing configuration
```

This PR https://github.com/3scale/rhamp-openshift-templates/pull/2 has the change.

Kindly review and merge.

**Comment by kasriniv** [comment]
Not sure if there are 2 issues and if they are related:
1. Saw this error when (I think) the wrong access token was used.
2. Additionally the pod status atleast once had "image pull error". This was a clue to image not being pulled.
I checked that the settings INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'
 proxy are per the guidance in the doc: https://support.3scale.net/docs/deployment-options/apicast-openshift
However, the only way I was able to get pass image pull error was to add registry.access.redhat.com to the image location yaml.

**Comment by rnc** [comment]
@kasriniv @VinayBhalerao What about adding --add-registry=registry.access.redhat.com to your docker configuration?

**Comment by mikz** [comment]
APIcast starts and tries to download configuration. That means there is no issue with the registry or pulling the image, but rather wrong access token that fails to download the configuration.

**Comment by mayorova** [comment]
I think there is a mix of two non-related issues here.
The `boot could not get configuration` was indeed due to the incorrect access token, as @kasriniv confirmed.

The real issue is that indeed if the GA OpenShift template is used (https://raw.githubusercontent.com/3scale/rhamp-openshift-templates/1.0.0.GA/apicast-gateway/apicast-gateway-template.yml), and the Red Hat registry is not configured, the image can't be pulled.

@rnc 
>What about adding --add-registry=registry.access.redhat.com to your docker configuration?

AFAIK this is only available on Red Hat's Docker package, not the one from [docker.com](https://www.docker.com/), is that correct?

So, if somebody is trying to use the template in another OS, he would indeed need to probably first download the `.yml` template, and add the registry.access.redhat.com to the image name.

But this is an issue with the productized APIcast, not this repo, so probably just the question of documentation (i.e. this issue can be closed).

**Comment by mikz** [comment]
I agree this is not really an issue of this repository can can be tracked somewhere else like in Jira / https://github.com/3scale/rhamp-openshift-templates/pull/2.
