### ISSUE TITLE
Return a 429 to the client when limits are exceeded

### ISSUE THREAD

**Issue by kevprice83** [3scale/apicast#368]
The issue is right now we return a `403 Authentication failed` when limits are exceeded. It would be much more useful for the client to know the specific reason in this case.

We essentially treat anything non 200 as an authentication failed.

**Comment by unleashed** [comment]
Would not it make more sense to return `429 Too Many Requests`? `409 Conflict` is not conveying that meaning at all.

**Comment by kevprice83** [comment]
Sorry for the typo, corrected...

**Comment by mikz** [comment]
@kevprice83 would be good to describe how to differentiate that in the backend response. (without parsing the xml body)

**Comment by mikz** [comment]
Also it should be defined if this status should be customizable from the UI like the other status codes.

**Comment by mayorova** [comment]
There's a meta issue here: https://issues.jboss.org/browse/THREESCALE-317
cc @mikz

**Comment by andrewdavidmackenzie** [comment]
Good idea to check in with Backend on current status, as some info is now being returned in Rate Limiting headers (reduced info compared to xml.... but a lot easier to parse).

**Comment by davidor** [comment]
I don't see a way to do this without parsing the response XML.

Backend returns 409 when limits are exceeded, but it also returns 409 in other cases. The only way to distinguish the reason is to parse the response XML and check the `reason` tag.

@mikz we have 2 options. Wait until backend provides a way to retrieve this information via headers in its public API or go ahead and solve this by parsing the XML.

**Comment by andrewdavidmackenzie** [comment]
response headers?

**Comment by MarkCheshire** [comment]
@david what are the other reasons for 429. In work done a long time ago I thought all the response codes from backend we're now clearly differentiated

**Comment by unleashed** [comment]
@MarkCheshire you surely mean `409`, not `429`. We have a list of such cases in the backend docs.

**Comment by hallelujah** [comment]
@unleashed 429 is for too many request
409 is conflict

**Comment by MarkCheshire** [comment]
Yes that is what I meant 409 (correcting). Below is what is listed in backend docs. I thought that 409 was only used for limits_exceeded. So two options 1) move the other error reasons to another code or 2) use a header to return the header reason so that APIcast does not have to open up the body.

authorization_failed: [409] Authorization denied because of rate limiting or wrong credentials

    limits_exceeded: The limit for a current period on a reported metric has been exceeded.
    oauth_not_enabled: The service does not have OAuth enabled.
    redirect_uri_invalid: The redirect URI does not match the one configured.
    redirect_url_invalid: See redirect_uri_invalid.
    application_not_active: The specified application is not active.
    application_key_invalid: Application key is missing or invalid
    referrer_not_allowed: The referrer specified does not match allowed referrers.

**Comment by davidor** [comment]
Changing the status code of all those errors is a breaking change. I think that doing this via headers is the way to go, but we need backend to include the headers we need in its stable API first.

**Comment by unleashed** [comment]
We are going to discuss this tomorrow.
