### ISSUE TITLE
Document and support exposing NGINX variables like response_time as a metric

### ISSUE THREAD

**Issue by vakrishn** [3scale/apicast#560]
It would be great to expose variables like response_time that are available in NGINX as a metric from 3Scale. We allude to adding more metrics, provide examples for overriding events to include this information in the logs etc. I can't think of too many clients who don't want response time as a metric just like rates etc.  

##### Version 3.0 ( 3Scale deployed in OpenShift On premise)

[provide output of the `nginx -V` or `openresty -V` command from openshift/local terminal]
[provide timestamp of the docker image from `docker inspect --format='{{.Created}}' quay.io/3scale/apicast:master` ]

##### Steps To Reproduce

1. [step 1 (json configuration file, if applies)]
2. [step 2 (curl commands to reproduce, if applies)]
3. [step 3]

##### Additional Information

* [Gist with minimal reproducible configuration, see guidelines for contributing for details]
* [Gist with nginx log output]

**Comment by MarkCheshire** [comment]
You would only want to report metrics to 3scale which are cumulative over time e.g. response size. 

Response time is a non-cumulative metric and it is also the type of operational metric that makes most sense when it is integrated into an Enterprise's standard availability and performance monitoring infrastructure, rather than into the 3scale admin portal which is better suited for business metrics.

It is easy to integrate response times with any monitoring tools because they are reported out into the logs: [https://github.com/3scale/apicast/blob/master/gateway/conf/nginx.conf.liquid#L44](https://github.com/3scale/apicast/blob/master/gateway/conf/nginx.conf.liquid#L44)

See also Nginx docs for the specification of the format: [http://nginx.org/en/docs/http/ngx_http_log_module.html#log_format](http://nginx.org/en/docs/http/ngx_http_log_module.html#log_format)
