### ISSUE TITLE
Add more documentation on Policies

### ISSUE THREAD

**Issue by lucamaf** [3scale/apicast#574]
At the moment the policies folder do not contain much info around how to use them/apply them and just a few example of how to actually configure their usage.

##### Expected Result
Ideally I would expect a Readme and Example of configuration for each policy created. Possibly also one example of policy chain configuration.

**Comment by davidor** [comment]
@lucamaf : this is what we have now regarding policies:

- General documentation on what policies are, how they work, and how you can write your own and integrate them in apicast  : https://github.com/3scale/apicast/blob/master/doc/policies.md
- Example about how to define a global policy chain: https://github.com/3scale/apicast/blob/master/examples/policy_chain/
- There's one more example coming: https://github.com/3scale/apicast/pull/581/
- Each policy has its own json schema, which should have a general description as well as descriptions for all the fields it accepts in the config. Also, most of the policies have documentation in the code.

Any feedback on any of all those is greatly appreciated (typos, grammar, things that are not clear, etc.)
We need to make sure that all of this is understood by users. Take into account that it will be easier once this is configurable via UI, but that cannot be an excuse not to have things well documented in Apicast.

What do you think we are missing @lucamaf ? I think that examples on each policy might be a bit overkill, because all of them are configure the same way.

Thanks for your suggestions @lucamaf

**Comment by davidor** [comment]
Since this issue was opened, we added more documentation in the policies doc (https://github.com/3scale/apicast/blob/master/doc/policies.md) , we also added more examples (https://github.com/3scale/apicast/tree/master/examples), and all the policies have documentation both in their schemas and the code. Also, now it's possible to configure the policies using the 3scale UI.

I'll close this for now. Feel free to reopen if you think we're missing something.
