### ISSUE TITLE
Define the nginx TLS configuration using environment variables

### ISSUE THREAD

**Issue by nmasse-itix** [3scale/apicast#609]
# Need

Some use cases require that nginx has a valid SSL/TLS configuration (such as client certificate authentication for instance). 

Currently, the customer has to write his nginx configuration templates that will be loaded by apicast in order to generate the final nginx configuration file. 

However, nginx configuration files defined in OpenShift Config Maps is error prone and not easily maintainable. 

It would be better if APIcast could generate the nginx configuration by itself using environment variables. 

# Proposition 

We could use the following environment variables : 
- APICAST_TLS_LISTEN={enable/disable} (optional, default = disable)
- APICAST_TLS_PORT=8443 (optional, default = 8443 if tls is enabled)
- APICAST_TLS_SERVING_CERTIFICATE=/path/to/tls.crt
- APICAST_TLS_SERVING_KEY=/path/to/tls.key
- APICAST_TLS_CRL=/path/to/file.crl (optional, none defined by default)
- APICAST_TLS_TRUSTED_CERTIFICATE=/path/to/ca-bundle.crt (optional, default to system bundle)
- APICAST_TLS_VERIFY_CLIENT={on/off/optional/optional_no_ca}
- APICAST_TLS_VERIFY_DEPTH= (optional, none defined by default)

There are other SSL/TLS configuration directives but they are less likely to change so they might be defined as nginx templates in ConfigMap or as custom image of APIcast.

**Comment by mikz** [comment]
@nmasse-itix we are implementing client certificate support for upstream connections in https://github.com/3scale/apicast/pull/610
Would be good if you could share your inputs regarding naming.

**Comment by mikz** [comment]
@nmasse-itix reviewing your proposal here are my suggestions: 

I'd try to get rid of `APICAST_TLS_LISTEN` and make it implicit by setting both the certificate and the key.

I'd change the `APICAST_TLS_` namespace to `APICAST_HTTPS_` to make it explicit that it is for HTTPS termination. There will be different settings for upstream connections: #610

Also I'm not sure if this is the best approach because we would basically expose every directive from http://nginx.org/en/docs/http/ngx_http_ssl_module.html as an option. It is a lot of variables. 

We are kind of postponing this decision until we have a solution we are going to be happy about. 
Maybe having the ability to control the nginx configuration from within a global policy (https://github.com/3scale/apicast/issues/477) would make this possible to be a global policy. Then we could give it some time to mature outside of the core before merging this upstream.

**Comment by nmasse-itix** [comment]
I like the `APICAST_HTTPS_` prefix ! 👍

**Comment by mikz** [comment]
For the record https://github.com/3scale/apicast/pull/610 introduced `APICAST_PROXY_HTTPS_*`  that control the TLS between APIcast and the upstream API (for now just client certificates).
