### ISSUE TITLE
expose objects available for liquid expressions and policies

### ISSUE THREAD

**Issue by mkudlej** [3scale/apicast#838]
It will be great to be able to see values stored in objects available for policy authors and used in liquid extensions. I mean these objects: 
 - line 5-8 https://github.com/3scale/apicast/blob/master/gateway/src/apicast/policy/ngx_variable.lua
 - plus JWT object
 - any other available in future

I think it will be great to have this in echo policy so user add echo policy into policy chain and user can create liquid expressions or write new policy based on values stored in exposed object.

Also I think it will be great to group all available objects to one root object (i.e. window or document object in Javascript in browsers).

**Comment by davidor** [comment]
I think it's better to put this functionality in a new policy. The echo policy has already a well-defined purpose and I'd rather leave it as it is.

We can create a new policy for debugging that logs the liquid context on every phase.

**Comment by mikz** [comment]
@davidor does the same limit apply to [`ngx.errlog.raw_log`](https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/errlog.md#raw_log) ? I guess so, because it uses `ngx_log_error` internally.

I think the policy could just create a response according to the Accept header (so text/plain or json). That way we would not be bounded by log limits and offer better feedback loop (curl would be enough).

**Comment by davidor** [comment]
Yes, the same limit applies to `errlog.raw_log`.
